/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ASTOperations;

import com.sun.source.tree.AnnotationTree;
import com.sun.source.tree.CaseTree;
import com.sun.source.tree.ClassTree;
import com.sun.source.tree.CompilationUnitTree;
import com.sun.source.tree.ConditionalExpressionTree;
import com.sun.source.tree.DoWhileLoopTree;
import com.sun.source.tree.EnhancedForLoopTree;
import com.sun.source.tree.ForLoopTree;
import com.sun.source.tree.IfTree;
import com.sun.source.tree.MethodTree;
import com.sun.source.tree.WhileLoopTree;
import com.sun.source.util.TreeScanner;
import java.util.List;
/**
 * Main scanner of the AST generated by the compilation task.
 * It is responsible for scanning the AST and processes any of the Tree nodes that are relevant
 * to the metrics produced if they exist.
 * 
 * @author ioannis
 */
public class ASTScanner extends TreeScanner<Void, Void> {
    
    public static Storage theStorage = new Storage();

    public ASTScanner(CompilationUnitTree compilationUnitTree) {
        List<? extends AnnotationTree> theTrees = compilationUnitTree.getPackageAnnotations();        
    }
    
    @Override
    public Void visitIf(IfTree arg0,Void a){
        theStorage.increaseIfTrees();
        theStorage.increaseComplexity();
        return super.visitIf(arg0, a);
    }
    
    @Override
    public Void visitWhileLoop(WhileLoopTree arg0, Void a){
        theStorage.increaseComplexity();
        return super.visitWhileLoop(arg0,a);
    
    }
    
    @Override
    public Void visitForLoop(ForLoopTree arg0, Void a){
        theStorage.increaseNoOfForLoops();
        return super.visitForLoop(arg0, a);
    }
    
    @Override
    public Void visitMethod(MethodTree arg0, Void a){
        String nb = arg0.getName().toString();
        if(!"<init>".equals(nb)){
            //System.out.println("Method: " +arg0.getName());
            theStorage.increaseMethodCount();
        }
        
        return super.visitMethod(arg0, a);
    }
    
    @Override
    public Void visitCase(CaseTree arg0, Void a) {
        theStorage.increaseComplexity();
        return super.visitCase(arg0, a);
    }

    @Override
    public Void visitConditionalExpression(ConditionalExpressionTree arg0, Void a) {
        theStorage.increaseComplexity();
        return super.visitConditionalExpression(arg0,a);
    }
    
    @Override
    public Void visitDoWhileLoop(DoWhileLoopTree arg0, Void a) {
        theStorage.increaseComplexity();
        return super.visitDoWhileLoop(arg0, a);
    }
    
    @Override
    public Void visitClass(ClassTree arg0, Void a){
        theStorage.increaseClassCount();
        return super.visitClass(arg0, a);
    }

    @Override
    public Void visitEnhancedForLoop(EnhancedForLoopTree arg0, Void a){
        theStorage.increaseNoOfForLoops();
        return super.visitEnhancedForLoop(arg0, a);
    }
    
}
